[tool.poetry]
name = "Assess Genes"
version = "0.1.0"
description = ""
authors = ["Yasemin Bridges"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
